apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.my-apps.tap.20240110055240.0.0+build.02e9424
spec:
  refName: where-for-dinner-search.my-apps.tap
  version: 20240110055240.0.0+build.02e9424
  releaseNotes: |
    Release v20240110055240.0.0+build.02e9424 of package where-for-dinner-search.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-09-01-2024-23-27-38-913712217/where-for-dinner-search-my-apps-bundle@sha256:95a98a1ee34b1b5c45dc2d08b14f662da62e85db56b1cc986ea2fb8378bc7c48
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

