apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240110055215.0.0+build.02e9424
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240110055215.0.0+build.02e9424
  releaseNotes: |
    Release v20240110055215.0.0+build.02e9424 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-09-01-2024-23-27-38-913712217/where-for-dinner-my-apps-bundle@sha256:e9b23e9bd8b329309ef339c3b227ce6ffc290a62ebd99269e5d507a1508dc3d1
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

