apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-notify.my-apps.tap.20240110055233.0.0+build.02e9424
spec:
  refName: where-for-dinner-notify.my-apps.tap
  version: 20240110055233.0.0+build.02e9424
  releaseNotes: |
    Release v20240110055233.0.0+build.02e9424 of package where-for-dinner-notify.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-09-01-2024-23-27-38-913712217/where-for-dinner-notify-my-apps-bundle@sha256:2040458aaf3bf0d039aa3ab8327e9b3f88c54a312177636376cdef72e8ca2b42
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

